#!/usr/bin/env bash
#
# vpnns-manager — run any app behind OpenVPN/NordVPN inside an isolated
# Linux network namespace, so SSH and host traffic keep the real IP while
# one app goes through the VPN. Interactive, config-driven, systemd-ready.
#
# Usage: vpnns.sh <command>
#   init             Interactive setup (writes config + auth.txt + edited .ovpn copy)
#   setup            Create namespace, veth, routing and NAT (idempotent)
#   start            Start OpenVPN inside the namespace (background)
#   stop             Stop OpenVPN
#   status           Show VPN state + host public IP vs namespace public IP
#   run [cmd...]     Run a command inside the namespace (defaults to APP_CMD)
#   shell            Open a shell inside the namespace
#   up               setup + start in foreground (used by systemd)
#   destroy          Tear everything down (idempotent)
#   install-service  Install + enable the systemd unit
#
set -euo pipefail

CONF="${VPNNS_CONF:-/etc/vpnns/vpnns.conf}"
SELF="$(readlink -f "$0")"

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo ">> $*"; }

require_root() {
  [[ "${EUID:-$(id -u)}" -eq 0 ]] || die "This command must be run as root."
}

load_conf() {
  [[ -f "$CONF" ]] || die "Config not found at $CONF. Run: $SELF init"
  # shellcheck disable=SC1090
  source "$CONF"
  : "${NS_NAME:?missing NS_NAME in config}"
  : "${VETH_HOST:?}" "${VETH_NS:?}" "${SUBNET:?}" "${HOST_IP:?}" "${NS_IP:?}"
  : "${DNS:?}" "${OVPN_WORK:?}" "${AUTH_FILE:?}" "${LOG_FILE:?}"
  APP_DIR="${APP_DIR:-}"
  APP_CMD="${APP_CMD:-}"
  EXT_IF="${EXT_IF:-}"
}

detect_ext_if() {
  if [[ -z "${EXT_IF:-}" ]]; then
    EXT_IF="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')"
  fi
  [[ -n "$EXT_IF" ]] || die "Could not detect the external interface (EXT_IF). Set it in $CONF."
}

# ---------------------------------------------------------------- init

cmd_init() {
  require_root
  local OVPN_SRC VPN_USER VPN_PASS NS SUBNET_IN DNS_IN APP_DIR_IN APP_CMD_IN

  read -rp "Path to your .ovpn file: " OVPN_SRC
  OVPN_SRC="${OVPN_SRC/#\~/$HOME}"
  OVPN_SRC="$(readlink -f "$OVPN_SRC" 2>/dev/null || echo "$OVPN_SRC")"
  [[ -f "$OVPN_SRC" ]] || die "File not found: $OVPN_SRC"

  read -rp "VPN username: " VPN_USER
  [[ -n "$VPN_USER" ]] || die "Username cannot be empty."
  read -rsp "VPN password: " VPN_PASS; echo
  [[ -n "$VPN_PASS" ]] || die "Password cannot be empty."

  read -rp "Namespace name [vpnns]: " NS;                       NS="${NS:-vpnns}"
  read -rp "Subnet base (third octet) [10.200.1]: " SUBNET_IN;  SUBNET_IN="${SUBNET_IN:-10.200.1}"
  read -rp "DNS servers [1.1.1.1 8.8.8.8]: " DNS_IN;            DNS_IN="${DNS_IN:-1.1.1.1 8.8.8.8}"
  read -rp "App working dir (optional): " APP_DIR_IN
  read -rp "App command (optional, e.g. 'python main.py'): " APP_CMD_IN

  mkdir -p /etc/vpnns

  local auth="/etc/vpnns/auth.txt"
  printf '%s\n%s\n' "$VPN_USER" "$VPN_PASS" > "$auth"
  chmod 600 "$auth"
  info "Wrote credentials to $auth (chmod 600)."

  # Edit only a COPY of the .ovpn; the original is never touched.
  local work="/etc/vpnns/$(basename "$OVPN_SRC")"
  cp "$OVPN_SRC" "$work"
  if grep -qE '^[[:space:]]*auth-user-pass' "$work"; then
    sed -i "s|^[[:space:]]*auth-user-pass.*|auth-user-pass $auth|" "$work"
  else
    printf 'auth-user-pass %s\n' "$auth" >> "$work"
  fi
  # Keep the namespace resolv.conf authoritative (don't let the server push DNS).
  grep -qF 'pull-filter ignore "dhcp-option DNS"' "$work" || \
    printf 'pull-filter ignore "dhcp-option DNS"\n' >> "$work"
  info "Wrote edited OpenVPN copy to $work (original untouched)."

  cat > "$CONF" <<EOF
# vpnns-manager configuration (generated by 'vpnns.sh init')
# WARNING: references credentials. Do NOT commit this file.
NS_NAME="$NS"
VETH_HOST="vh-$NS"
VETH_NS="vp-$NS"
SUBNET="$SUBNET_IN"
HOST_IP="$SUBNET_IN.1"
NS_IP="$SUBNET_IN.2"
DNS="$DNS_IN"
OVPN_WORK="$work"
AUTH_FILE="$auth"
APP_DIR="$APP_DIR_IN"
APP_CMD="$APP_CMD_IN"
LOG_FILE="/var/log/vpnns-$NS.log"
# Leave EXT_IF empty for auto-detection, or pin it (e.g. eth0).
EXT_IF=""
EOF
  chmod 600 "$CONF"
  info "Config written to $CONF"
  info "Next: $SELF setup && $SELF start && $SELF status"
}

# ---------------------------------------------------------------- setup

cmd_setup() {
  require_root; load_conf; detect_ext_if

  # Idempotent teardown of any previous instance of THIS namespace.
  ip netns pids "$NS_NAME" 2>/dev/null | xargs -r kill 2>/dev/null || true
  ip netns delete "$NS_NAME" 2>/dev/null || true
  ip link delete "$VETH_HOST" 2>/dev/null || true

  info "Creating namespace $NS_NAME"
  ip netns add "$NS_NAME"

  info "Creating veth pair $VETH_HOST <-> $VETH_NS"
  ip link add "$VETH_HOST" type veth peer name "$VETH_NS"
  ip link set "$VETH_NS" netns "$NS_NAME"

  ip addr add "$HOST_IP/24" dev "$VETH_HOST"
  ip link set "$VETH_HOST" up

  ip netns exec "$NS_NAME" ip addr add "$NS_IP/24" dev "$VETH_NS"
  ip netns exec "$NS_NAME" ip link set "$VETH_NS" up
  ip netns exec "$NS_NAME" ip link set lo up
  ip netns exec "$NS_NAME" ip route add default via "$HOST_IP"

  info "Configuring namespace DNS"
  mkdir -p "/etc/netns/$NS_NAME"
  : > "/etc/netns/$NS_NAME/resolv.conf"
  for ns in $DNS; do
    printf 'nameserver %s\n' "$ns" >> "/etc/netns/$NS_NAME/resolv.conf"
  done

  info "Enabling IPv4 forwarding"
  sysctl -wq net.ipv4.ip_forward=1

  info "Adding NAT/forward rules via $EXT_IF (idempotent)"
  iptables -t nat -C POSTROUTING -s "$SUBNET.0/24" -o "$EXT_IF" -j MASQUERADE 2>/dev/null \
    || iptables -t nat -A POSTROUTING -s "$SUBNET.0/24" -o "$EXT_IF" -j MASQUERADE
  iptables -C FORWARD -i "$VETH_HOST" -o "$EXT_IF" -j ACCEPT 2>/dev/null \
    || iptables -A FORWARD -i "$VETH_HOST" -o "$EXT_IF" -j ACCEPT
  iptables -C FORWARD -i "$EXT_IF" -o "$VETH_HOST" -m state --state RELATED,ESTABLISHED -j ACCEPT 2>/dev/null \
    || iptables -A FORWARD -i "$EXT_IF" -o "$VETH_HOST" -m state --state RELATED,ESTABLISHED -j ACCEPT

  info "Namespace base connectivity test"
  ip netns exec "$NS_NAME" ping -c2 -W3 "$HOST_IP" >/dev/null && info "  veth link OK"
  ip netns exec "$NS_NAME" ping -c2 -W3 1.1.1.1 >/dev/null && info "  internet OK"
  info "setup complete."
}

# ---------------------------------------------------------------- start/stop

openvpn_pid() {
  pgrep -f "openvpn --config $OVPN_WORK" || true
}

cmd_start() {
  require_root; load_conf
  [[ -f "$OVPN_WORK" ]] || die "OpenVPN config missing: $OVPN_WORK (run init)"
  ip netns list | grep -qw "$NS_NAME" || die "Namespace $NS_NAME missing. Run: $SELF setup"

  if [[ -n "$(openvpn_pid)" ]]; then
    info "OpenVPN already running (pid $(openvpn_pid))."; return 0
  fi

  info "Starting OpenVPN in $NS_NAME (log: $LOG_FILE)"
  : > "$LOG_FILE"
  nohup ip netns exec "$NS_NAME" openvpn --config "$OVPN_WORK" \
    >> "$LOG_FILE" 2>&1 &

  info "Waiting for tunnel..."
  for _ in $(seq 1 30); do
    if grep -q "Initialization Sequence Completed" "$LOG_FILE" 2>/dev/null; then
      info "VPN connected."
      # Re-assert DNS in case anything rewrote it.
      mkdir -p "/etc/netns/$NS_NAME"
      : > "/etc/netns/$NS_NAME/resolv.conf"
      for ns in $DNS; do printf 'nameserver %s\n' "$ns" >> "/etc/netns/$NS_NAME/resolv.conf"; done
      return 0
    fi
    sleep 1
  done
  echo "---- last log lines ----"; tail -n 30 "$LOG_FILE" || true
  die "Timed out waiting for 'Initialization Sequence Completed'. Check $LOG_FILE"
}

cmd_stop() {
  require_root; load_conf
  local pid; pid="$(openvpn_pid)"
  if [[ -n "$pid" ]]; then
    info "Stopping OpenVPN (pid $pid)"; kill $pid 2>/dev/null || true
    sleep 1
    pid="$(openvpn_pid)"; [[ -n "$pid" ]] && kill -9 $pid 2>/dev/null || true
  else
    info "OpenVPN not running."
  fi
}

# ---------------------------------------------------------------- status

cmd_status() {
  load_conf
  local pid host_ip ns_ip tun
  pid="$(openvpn_pid)"
  echo "Namespace          : $NS_NAME"
  echo "OpenVPN            : ${pid:-not running}"
  tun="$(ip netns exec "$NS_NAME" ip -o link show type tun 2>/dev/null | awk -F': ' '{print $2}' | paste -sd, -)"
  echo "Tunnel             : ${tun:-none}"

  host_ip="$(curl -4 -s --max-time 8 ifconfig.me || echo 'n/a')"
  ns_ip="$(ip netns exec "$NS_NAME" curl -4 -s --max-time 8 ifconfig.me 2>/dev/null || echo 'n/a')"
  echo "Host public IP     : $host_ip"
  echo "Namespace public IP: $ns_ip"
  if [[ "$host_ip" != "n/a" && "$ns_ip" != "n/a" && "$host_ip" != "$ns_ip" ]]; then
    echo "Result             : OK — namespace traffic is going through the VPN."
  else
    echo "Result             : NOT isolated — IPs match or unavailable. Check 'start' / logs."
  fi
  echo "----- last log lines ($LOG_FILE) -----"
  tail -n 15 "$LOG_FILE" 2>/dev/null || echo "(no log yet)"
}

# ---------------------------------------------------------------- run/shell

cmd_run() {
  require_root; load_conf
  if [[ $# -gt 0 ]]; then
    ip netns exec "$NS_NAME" bash -lc "$*"
  elif [[ -n "$APP_CMD" ]]; then
    ip netns exec "$NS_NAME" bash -lc "cd '${APP_DIR:-/}' 2>/dev/null; $APP_CMD"
  else
    die "No command given and APP_CMD is empty in config."
  fi
}

cmd_shell() {
  require_root; load_conf
  exec ip netns exec "$NS_NAME" bash
}

# ---------------------------------------------------------------- up (systemd)

cmd_up() {
  cmd_setup
  load_conf
  [[ -f "$OVPN_WORK" ]] || die "OpenVPN config missing: $OVPN_WORK"
  info "Running OpenVPN in foreground (systemd mode)"
  exec ip netns exec "$NS_NAME" openvpn --config "$OVPN_WORK"
}

# ---------------------------------------------------------------- destroy

cmd_destroy() {
  require_root
  load_conf || true
  detect_ext_if 2>/dev/null || true

  local pid; pid="$(openvpn_pid 2>/dev/null || true)"
  [[ -n "$pid" ]] && { info "Killing OpenVPN $pid"; kill $pid 2>/dev/null || true; }
  ip netns pids "$NS_NAME" 2>/dev/null | xargs -r kill 2>/dev/null || true

  if [[ -n "${EXT_IF:-}" ]]; then
    iptables -t nat -D POSTROUTING -s "$SUBNET.0/24" -o "$EXT_IF" -j MASQUERADE 2>/dev/null || true
    iptables -D FORWARD -i "$VETH_HOST" -o "$EXT_IF" -j ACCEPT 2>/dev/null || true
    iptables -D FORWARD -i "$EXT_IF" -o "$VETH_HOST" -m state --state RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || true
  fi

  ip netns delete "$NS_NAME" 2>/dev/null || true
  ip link delete "$VETH_HOST" 2>/dev/null || true
  rm -f "/etc/netns/$NS_NAME/resolv.conf" 2>/dev/null || true
  rmdir "/etc/netns/$NS_NAME" 2>/dev/null || true
  info "destroyed (idempotent)."
}

# ---------------------------------------------------------------- service

cmd_install_service() {
  require_root
  local src dst="/etc/systemd/system/vpnns.service"
  src="$(dirname "$SELF")/systemd/vpnns.service"
  install -m 0755 "$SELF" /usr/local/bin/vpnns.sh
  [[ -f "$src" ]] || die "Unit file not found: $src"
  install -m 0644 "$src" "$dst"
  systemctl daemon-reload
  systemctl enable vpnns.service
  info "Installed. Start now with: systemctl start vpnns.service"
}

usage() {
  sed -n '7,17p' "$SELF" | sed 's/^# \{0,1\}//'
}

main() {
  local cmd="${1:-}"; shift || true
  case "$cmd" in
    init)            cmd_init "$@" ;;
    setup)           cmd_setup "$@" ;;
    start)           cmd_start "$@" ;;
    stop)            cmd_stop "$@" ;;
    status)          cmd_status "$@" ;;
    run)             cmd_run "$@" ;;
    shell)           cmd_shell "$@" ;;
    up)              cmd_up "$@" ;;
    destroy)         cmd_destroy "$@" ;;
    install-service) cmd_install_service "$@" ;;
    ""|-h|--help|help) usage ;;
    *) echo "Unknown command: $cmd"; echo; usage; exit 1 ;;
  esac
}

main "$@"
